export const endpoints = {
  navbar: "navbar",
  home: "home-page",
  academics: "academics-page",
  programs: "academic-programs",
  about: "about-us-page",
  research: "research-page",
  researchers: "researchers",
  posts: "posts",
  postspage: "posts-page",
  socialservicepage: "social-service-page",
  workplacement: "work-placement-page",
  servicespage: "services-page",
  universitypage: "university-page",
  studentspage: "students-page",
  footer: "footer",
};
